
export const metadata = {
    title: 'Create N App',
    description: 'Generated by create next app',
  }
export default async function About(){

    // it should be inside function or something when error happens
    // throw new Error("failed to load")

   
    return(
        <div>
            <h1>About</h1>
            <p>haha</p>
            <p className=" font-montserrat">haha</p>
            

        </div>
    )
}